repos:
  - repo: local
    hooks:
      - id: check-restricted-files
        name: Check for .json, .jsonl or .csv files
        entry: python3 .pre-commit-hooks/check_for_restricted_files.py
        language: system
        types: [file]
        pass_filenames: true
