name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Test Common
      run: go test -v ./common/...

    - name: Build Transmit
      run: go build -v ./mock/transmit/...

    - name: Build Master
      run: go build -v ./services/master/...

    - name: Build Visunator
      run: go build -v ./visunator/...
