name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install libzmq3-dev
      run: sudo apt install libzmq3-dev

    - name: Test Common
      working-directory: ./common
      run: go test -v ./...

    - name: Build Transmit
      working-directory: ./mock/transmit
      run: go build -v ./...

    - name: Build Master
      working-directory: ./services/master
      run: go build -v ./...

    - name: Build Visunator
      working-directory: ./visunator
      run: go build -v ./...
